[Interface]
PrivateKey = QNIvCdKTbzm1ILioprkJ4p2708EwYrP/HUFMWvoOPEs=
Address = 10.0.0.2/24
DNS = 8.8.8.8

[Peer]
PublicKey = g6E+revbfe+4HaSGtZB5KAKzjGL6KLel+AQPBO1eUE8=
Endpoint = 87.107.109.98:51820
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25
