"""
WAF Detection and Bypass Scanner
Identifies WAFs and tests bypass techniques
"""
import re
from typing import List, Optional, Dict
from .base import BaseScanner, Vulnerability, Severity


class WAFBypassScanner(BaseScanner):
    """WAF detection and bypass scanner"""
    
    def __init__(self, http_client, engine=None):
        super().__init__(http_client, engine)
        self.name = "WAF Detection & Bypass Scanner"
        
        # WAF fingerprints
        self.waf_patterns = {
            "Cloudflare": [
                r"cloudflare",
                r"cf-ray",
                r"__cfduid",
                r"cf-cache-status",
            ],
            "AWS WAF": [
                r"aws",
                r"x-amzn-requestid",
                r"x-amzn-trace-id",
            ],
            "ModSecurity": [
                r"mod_security",
                r"modsecurity",
                r"this error was generated by mod_security",
            ],
            "Akamai": [
                r"akamai",
                r"akamaighost",
            ],
            "Incapsula": [
                r"incapsula",
                r"visid_incap",
            ],
            "Sucuri": [
                r"sucuri",
                r"x-sucuri-id",
            ],
            "Barracuda": [
                r"barracuda",
                r"barra_counter_session",
            ],
            "F5 BigIP": [
                r"bigip",
                r"f5",
                r"x-wa-info",
            ],
        }
        
        # Bypass techniques
        self.bypass_payloads = {
            "SQLi": [
                "admin'/**/or/**/1=1--",
                "admin'/*!or*/1=1--",
                "admin'%0aor%0a1=1--",
                "admin'/**/UNION/**/SELECT/**/NULL--",
                "admin'/**/UNIoN/**/SeLeCt/**/NULL--",
            ],
            "XSS": [
                "<img src=x onerror=alert(1)>",
                "<svg/onload=alert(1)>",
                "<script>alert(String.fromCharCode(88,83,83))</script>",
                "<iframe src=javascript:alert(1)>",
                "<body onload=alert(1)>",
            ],
        }
    
    async def scan(self, url: str, **kwargs) -> List[Vulnerability]:
        """Scan for WAF and test bypass techniques"""
        vulnerabilities = []
        
        # Detect WAF
        detected_waf = await self._detect_waf(url)
        if detected_waf:
            vuln = self._create_vulnerability(
                name=f"WAF Detected: {detected_waf}",
                severity=Severity.INFO,
                url=url,
                description=f"Web Application Firewall detected: {detected_waf}",
                evidence=f"WAF fingerprint matched: {detected_waf}",
                recommendation="Ensure WAF is properly configured and up to date",
                cwe="CWE-693"
            )
            vulnerabilities.append(vuln)
            
            # Test bypass techniques
            bypass_vulns = await self._test_waf_bypass(url, detected_waf)
            vulnerabilities.extend(bypass_vulns)
        
        return vulnerabilities
    
    async def _detect_waf(self, url: str) -> Optional[str]:
        """Detect WAF from response headers and content"""
        try:
            resp = await self.http_client.get(url, timeout=10)
            
            # Check headers
            headers_str = str(resp.headers).lower()
            for waf_name, patterns in self.waf_patterns.items():
                for pattern in patterns:
                    if re.search(pattern, headers_str, re.IGNORECASE):
                        return waf_name
            
            # Check response body
            body_lower = resp.text.lower()
            for waf_name, patterns in self.waf_patterns.items():
                for pattern in patterns:
                    if re.search(pattern, body_lower, re.IGNORECASE):
                        return waf_name
            
            # Check for WAF block pages
            waf_block_indicators = [
                "access denied",
                "forbidden",
                "blocked",
                "security",
                "firewall",
                "your request has been blocked",
            ]
            
            if any(indicator in body_lower for indicator in waf_block_indicators):
                # Try to identify specific WAF
                if "cloudflare" in body_lower:
                    return "Cloudflare"
                elif "mod_security" in body_lower:
                    return "ModSecurity"
        except:
            pass
        
        return None
    
    async def _test_waf_bypass(self, url: str, waf_name: str) -> List[Vulnerability]:
        """Test WAF bypass techniques"""
        vulnerabilities = []
        
        # Test SQLi bypass
        for payload in self.bypass_payloads["SQLi"]:
            try:
                test_url = f"{url}?id={payload}"
                resp = await self.http_client.get(test_url, timeout=5)
                
                # Check if payload bypassed WAF
                if resp.status_code == 200 and "sql" in resp.text.lower():
                    vuln = self._create_vulnerability(
                        name=f"WAF Bypass: SQL Injection ({waf_name})",
                        severity=Severity.HIGH,
                        url=test_url,
                        payload=payload,
                        description=f"WAF bypass technique successful for {waf_name}",
                        evidence=f"SQL injection payload bypassed WAF: {payload}",
                        recommendation="Update WAF rules and implement additional input validation",
                        cwe="CWE-943"
                    )
                    vulnerabilities.append(vuln)
                    break
            except:
                continue
        
        # Test XSS bypass
        for payload in self.bypass_payloads["XSS"]:
            try:
                test_url = f"{url}?q={payload}"
                resp = await self.http_client.get(test_url, timeout=5)
                
                # Check if payload is reflected
                if payload in resp.text and resp.status_code == 200:
                    vuln = self._create_vulnerability(
                        name=f"WAF Bypass: XSS ({waf_name})",
                        severity=Severity.HIGH,
                        url=test_url,
                        payload=payload,
                        description=f"XSS payload bypassed WAF: {waf_name}",
                        evidence=f"XSS payload reflected in response: {payload}",
                        recommendation="Update WAF rules and implement output encoding",
                        cwe="CWE-79"
                    )
                    vulnerabilities.append(vuln)
                    break
            except:
                continue
        
        return vulnerabilities

